app_root:
    path: /
    defaults: { _controller: 'AppBundle:Default:index' }

app_nelmio_demo_anotations_get:
    path: /getA
    methods: GET
    defaults: { _controller: 'AppBundle:NelmioAnnotation:get'}

app_nelmio_demo_anotations_post:
    path: /postA
    methods: POST
    defaults: { _controller: 'AppBundle:NelmioAnnotation:post'}

app_nelmio_demo_anotations_cget:
    path: /cgetA
    methods: GET
    defaults: { _controller: 'AppBundle:NelmioAnnotation:cget'}

